AAOAAOAAif [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
  fi
fi
if [ -e usr/share/glib-2.0/schemas ]; then
  if [ -x /usr/bin/glib-compile-schemas ]; then
    /usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
  fi
fi

( cd usr/share/help/ca/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/ca/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/ca/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/ca/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/ca/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/ca/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/ca/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/ca/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/cs/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/cs/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/cs/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/cs/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/cs/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/cs/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/cs/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/cs/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/da/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/da/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/da/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/da/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/da/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/da/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/da/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/da/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/de/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/de/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/de/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/de/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/de/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/de/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/de/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/de/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/el/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/el/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/el/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/el/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/el/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/el/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/el/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/el/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/es/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/es/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/es/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/es/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/es/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/es/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/es/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/es/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/eu/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/eu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/eu/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/eu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/eu/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/eu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/eu/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/eu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/fr/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/fr/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/fr/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/fr/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/fr/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/fr/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/fr/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/fr/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/gl/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/gl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/gl/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/gl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/gl/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/gl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/gl/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/gl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/hu/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/hu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/hu/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/hu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/hu/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/hu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/hu/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/hu/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/ja/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/ja/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/ja/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/ja/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/ja/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/ja/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/ja/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/ja/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/ko/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/ko/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/ko/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/ko/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/ko/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/ko/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/ko/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/ko/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/pl/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/pl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/pl/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/pl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/pl/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/pl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/pl/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/pl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/pt_BR/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/pt_BR/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/pt_BR/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/sl/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/sl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/sl/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/sl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/sl/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/sl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/sl/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/sl/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/sv/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/sv/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/sv/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/sv/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/sv/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/sv/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/sv/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/sv/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )
( cd usr/share/help/uk/gnome-mines/figures ; rm -rf flag-question.svg )
( cd usr/share/help/uk/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag-question.svg flag-question.svg )
( cd usr/share/help/uk/gnome-mines/figures ; rm -rf flag.svg )
( cd usr/share/help/uk/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flag.svg flag.svg )
( cd usr/share/help/uk/gnome-mines/figures ; rm -rf flags.png )
( cd usr/share/help/uk/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/flags.png flags.png )
( cd usr/share/help/uk/gnome-mines/figures ; rm -rf org.gnome.Mines.svg )
( cd usr/share/help/uk/gnome-mines/figures ; ln -sf ../../../C/gnome-mines/figures/org.gnome.Mines.svg org.gnome.Mines.svg )

